name: Auth Safeguards

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  deployment_status:

jobs:
  audit-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: Check if secrets are available
        id: check-secrets
        run: |
          if [ -z "${{ secrets.GOOGLE_CLIENT_ID }}" ] || [ -z "${{ secrets.NEXTAUTH_SECRET }}" ]; then
            echo "secrets_available=false" >> $GITHUB_OUTPUT
            echo "⚠️ GitHub Secrets not configured yet. Skipping environment audit."
          else
            echo "secrets_available=true" >> $GITHUB_OUTPUT
          fi
      - name: ENV audit (prod)
        if: steps.check-secrets.outputs.secrets_available == 'true'
        env:
          NEXTAUTH_URL: https://www.clarnote.com
          AUTH_TRUST_HOST: true
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run audit:env
      - name: Skip ENV audit
        if: steps.check-secrets.outputs.secrets_available == 'false'
        run: echo "⏭️ Skipping ENV audit - GitHub Secrets not configured"

  smoke-prod:
    runs-on: ubuntu-latest
    needs: audit-env
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Auth smoke (prod)
        env:
          AUTH_TEST_URL: https://www.clarnote.com
        run: npm run test:auth:prod

  smoke-staging:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Check if staging exists
        id: check-staging
        run: |
          if curl -s --head https://staging.clarnote.com | head -n 1 | grep -q "200 OK"; then
            echo "staging_available=true" >> $GITHUB_OUTPUT
          else
            echo "staging_available=false" >> $GITHUB_OUTPUT
            echo "⚠️ Staging environment not available yet."
          fi
      - name: Auth smoke (staging)
        if: steps.check-staging.outputs.staging_available == 'true'
        env:
          AUTH_TEST_URL: https://staging.clarnote.com
        run: npm run test:auth:staging
      - name: Skip staging tests
        if: steps.check-staging.outputs.staging_available == 'false'
        run: echo "⏭️ Skipping staging tests - staging.clarnote.com not available" 